openapi: 3.0.0
info:
  title: TGS E-Learning API
  version: 1.0.0
  description: API documentation for the SCORM-based e-learning system

servers:
  - url: http://localhost:3000/api
    description: Development server

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    User:
      type: object
      properties:
        id:
          type: string
        email:
          type: string
        role:
          type: string
          enum: [admin, instructor, student]
        name:
          type: string

    Course:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
        scormVersion:
          type: string
          enum: [1.2, 2004]

paths:
  /users/login:
    post:
      summary: User login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                  user:
                    $ref: '#/components/schemas/User'

  /courses:
    get:
      summary: Get all courses
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of courses
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Course' 